### ISSUE TITLE
How do you get data from the form ? 

### ISSUE THREAD

**Issue by The-Real-Thisas** [FrigadeHQ/react-native-onboard#10]
Sorry, new to react native so this may be something simple. 

But in this demo https://snack.expo.dev/@christian-frigade/react-native-onboard-form-demo?platform=ios , the data is taken in but I don't see a prop to access the data. Would it be possible to modify the snack to perhaps store the data in asyncStorage. I also don't see this in the documentation and the documentation relates to Frigade and not how to use this module.

Thank you.

**Comment by Nathanael-R** [comment]
@The-Real-Thisas  

You can use the onSetText prop to save the value of each input and use the onDone Prop to stringify the state data and store to AsyncStorage 

Here's a mini example
import React from "react";
import { Text, View, StyleSheet } from "react-native";
import { OnboardFlow } from "react-native-onboard";

export default function App() {
  const [formFieldValues, setFormFieldValues] = React.useState({
    email: "",
    firstName: "",
    lastName: "",
  });

  const handleEmailChange = (text) => {
    setFormFieldValues((prev) => ({
      ...prev,
      email: text,
    }));
  };

  const firstNameData = (text) => {
    setFormFieldValues((prevState) => ({
      ...prevState,
      firstName: text,
    }));
  };

  const lastNameData = (text) => {
    setFormFieldValues((prevState) => ({
      ...prevState,
      lastName: text,
    }));
  };
  const handleSaveData = () => {
    console.log("Saving form data:", formFieldValues);
  };
  const saveData = () => {
    console.log("Saved:", formFieldValues)
  }
 
  return (
    <View style={styles.container}>
      <OnboardFlow
        pages={[
          {
            title: "Welcome to my app",
            subtitle: "Connect your bank account now and start saving money.",
            imageUri: "https://frigade.com/img/demo.png",
          },
          {
            title: "What is your e-mail?",
            subtitle: "We promise not to spam ✌️",
            type: "formEntry",
            primaryButtonTitle: "Request access",
            props: {
              fields: [
                {
                  type: "email",
                  id: "email",
                  placeHolder: "Email",
                  label: "Email Address",
                  isRequired: true,
                  onSetText: handleEmailChange,
                },
              ],
            },
          },
          {
            title: "What's your full name?",
            type: "formEntry",
            primaryButtonTitle: "Continue",
            props: {
              fields: [
                {
                  type: "text",
                  id: "firstName",
                  placeHolder: "First name",
                  label: "First name",
                  isRequired: false,
                  onSetText: firstNameData,
                },
                {
                  type: "text",
                  id: "lastName",
                  placeHolder: "Last name",
                  label: "Last name",
                  isRequired: false,
                  onSetText: lastNameData,
                },
              ],
            },
          },
        ]}
        onSaveData={handleSaveData}
        onDone={saveData}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

**Comment by Nathanael-R** [comment]
@The-Real-Thisas  

Use the onSetText to save the value of each input and use the onDone Prop to store the data to AsyncStorage 

```
import React from "react";
import { Text, View, StyleSheet } from "react-native";
import { OnboardFlow } from "react-native-onboard";

export default function App() {
  const [formFieldValues, setFormFieldValues] = React.useState({
    email: "",
    firstName: "",
    lastName: "",
  });

  const handleEmailChange = (text) => {
    setFormFieldValues((prev) => ({
      ...prev,
      email: text,
    }));
  };

  const firstNameData = (text) => {
    setFormFieldValues((prevState) => ({
      ...prevState,
      firstName: text,
    }));
  };

  const lastNameData = (text) => {
    setFormFieldValues((prevState) => ({
      ...prevState,
      lastName: text,
    }));
  };
  const handleSaveData = () => {
    console.log("Saving form data:", formFieldValues);
  };
  const saveData = () => {
    console.log("Saved:", formFieldValues)
  }
 
  return (
    <View style={styles.container}>
      <OnboardFlow
        pages={[
          {
            title: "Welcome to my app",
            subtitle: "Connect your bank account now and start saving money.",
            imageUri: "https://frigade.com/img/demo.png",
          },
          {
            title: "What is your e-mail?",
            subtitle: "We promise not to spam ✌️",
            type: "formEntry",
            primaryButtonTitle: "Request access",
            props: {
              fields: [
                {
                  type: "email",
                  id: "email",
                  placeHolder: "Email",
                  label: "Email Address",
                  isRequired: true,
                  onSetText: handleEmailChange,
                },
              ],
            },
          },
          {
            title: "What's your full name?",
            type: "formEntry",
            primaryButtonTitle: "Continue",
            props: {
              fields: [
                {
                  type: "text",
                  id: "firstName",
                  placeHolder: "First name",
                  label: "First name",
                  isRequired: false,
                  onSetText: firstNameData,
                },
                {
                  type: "text",
                  id: "lastName",
                  placeHolder: "Last name",
                  label: "Last name",
                  isRequired: false,
                  onSetText: lastNameData,
                },
              ],
            },
          },
        ]}
        onSaveData={handleSaveData}
        onDone={saveData}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

```

**Comment by The-Real-Thisas** [comment]
Thanks, this solves my question. Would be helpful if it were in the docs.

**Comment by Nathanael-R** [comment]
> Thanks, this solves my question. Would be helpful if it were in the docs.

@christianmat Is there any way I can help with this?
