### ISSUE TITLE
How to Create Tooltip/Walkthrough as Shown in Main Screenshot?

### ISSUE THREAD

**Issue by francisseverino** [FrigadeHQ/react-native-onboard#19]
I noticed a walkthrough tooltip in the main screenshot of this project and I'm interested in implementing something similar. However, I couldn't find relevant instructions in the documentation or codebase.

Could anyone provide insights or direct me to the appropriate resources for creating a tooltip/walkthrough as shown in the screenshot?

Thanks for any help!
<img width="289" alt="Screenshot 2024-01-16 at 1 11 30 PM" src="https://github.com/FrigadeHQ/react-native-onboard/assets/40039248/40237b20-2c6d-4564-899c-68e65b001b88">

**Comment by brownrout** [comment]
Hey, that was part of our roadmap but we’ve focused our time since then on our React library, instead.
