### ISSUE TITLE
Error: No native splash screen registered for given view controller.

### ISSUE THREAD

**Issue by cip123** [FrigadeHQ/react-native-onboard#7]
I am getting the following error when using it with `expo-splash-screen` and `SplashScreen.hideAsync();` 

This only happens when I first launch the app on iOs simulator.

```
Error: No native splash screen registered for the given view controller. Call 'SplashScreen.show' for given view controller first.
```
This happens when one component tries to render something before the splash screen is hidden.  I call the `SplashScreen.hideAsync()`  within a timeout onLayoutView. I think I can find a workaround for it. 

I am leaving this issue open at the moment.

**Comment by cip123** [comment]
Ok, I am closing this. This thing was rendering before I hid the splash screen.

**Comment by sokunsamnang** [comment]
how you solve this issues ?
