### ISSUE TITLE
Horizontal scrolling for smaller screens

### ISSUE THREAD

**Issue by cip123** [FrigadeHQ/react-native-onboard#8]
Hello, what solution do you suggest for smaller screens that may even have increased font sizes? At the moment, if the text is too long, it is getting clipped.

**Comment by christianmat** [comment]
Hey @cip123, feel free to open a PR if you have a fix in mind for the above bug.

**Comment by cip123** [comment]
Hey @christianmat it looks like this was added by https://github.com/FrigadeHQ/react-native-onboard/commit/4bb497f0b71836b45148a045d4f7284d3dbc9a92 but it is not released yet.

**Comment by christianmat** [comment]
This is now released
